on: push

name: CI

jobs:
  ci:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        rust:
          - stable
          - 1.65.0

    steps:
      - uses: actions/checkout@v2

      - name: Check docs
        run: |
          ./scripts/update-docs
          if [[ $(git status --porcelain | wc -l) != 0 ]] ; then
              echo "Nede to run ./scripts/update-docs."
              exit -1
          fi

      - name: Build and test
        run: |
          cargo run -p testing
